### ISSUE TITLE
Command line for real devices

### ISSUE THREAD

**Issue by licollins** [husam88/DroidbotX#2]
Hi,

I am trying to run in a real device using the command python start_q_learning.py -a app-debug.apk -o my_output_dir/ -d "device serial number" -policy gym
But  the droidbot  is returning [CONNECTION] ADB is disconnected
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
Is this command line incorrect?

**Comment by licollins** [comment]
I fixed creating an anaconda environment using Python 3.7 and tensorflow==1.14

**Comment by husam88** [comment]
please test your environment by running Droidbot on a real device first, using this command 
droidbot -a <path_to_apk> -o output_dir -d "device serial number"
